CREATE VIEW AMBULATORY_MAPPING AS
SELECT b.CAMPUS, b.CAMPUS_SPECIALTY, b.DEPARTMENT_OLD, b.DEPARTMENT, b.DEPARTMENT_ID, d.LAST_ARRIVED
FROM(
SELECT a.*, regexp_replace(DEPARTMENT_OLD,'_DEACTIVATED|X_','') AS DEPARTMENT
FROM(
    SELECT distinct CAMPUS, CAMPUS_SPECIALTY, DEPARTMENT AS DEPARTMENT_OLD, DEPARTMENT_ID
    FROM ambulatory_access_table where APPT_STATUS = 'Arrived'
    ) a
   ) b 
    LEFT JOIN
    (SELECT c.*
       FROM(
          SELECT DEPARTMENT_ID, max(APPT_DTTM) as LAST_ARRIVED
          FROM ambulatory_access_table where APPT_STATUS = 'Arrived'
          GROUP BY DEPARTMENT_ID
          ) c
          ) d
          on b.DEPARTMENT_ID= d.DEPARTMENT_ID







CREATE VIEW UTILIZATION_VIEW As
Select a.* , b.campus, b.CAMPUS_SPECIALTY, b.DEPARTMENT, b.DEPARTMENT_OLD
From UTILIZATION_TABLE a

LEFT JOIN AMBULATORY_MAPPING b on a.DEPARTMENT_ID = b.DEPARTMENT_ID


