CREATE VIEW AMBULATORY_MAPPING AS
SELECT a.*, regexp_replace(DEPARTMENT_OLD,'_DEACTIVATED|X_','') AS DEPARTMENT,
       CASE CAMPUS_OLD WHEN 'MSDD' THEN 'MSDMG' ELSE CAMPUS_OLD END AS CAMPUS
FROM(
        SELECT distinct CAMPUS AS CAMPUS_OLD, CAMPUS_SPECIALTY, DEPARTMENT AS DEPARTMENT_OLD, DEPARTMENT_ID
        FROM AMBULATORY_ACCESS_TABLE
    ) a
